ALTER TABLE reviews
  MODIFY COLUMN customer_id BIGINT UNSIGNED NULL,
  MODIFY COLUMN order_item_id BIGINT UNSIGNED NULL,
  ADD COLUMN admin_id BIGINT UNSIGNED NULL DEFAULT NULL AFTER order_item_id,
  ADD CONSTRAINT fk_reviews_admin FOREIGN KEY (admin_id) REFERENCES admins(id) ON DELETE SET NULL;
